# Generated by Django 5.0.2 on 2026-05-04 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, db_index=True, editable=False, help_text='Unique ticket number (9-character alphanumeric string)', max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, choices=[('email', 'Email'), ('web', 'Web/Portal'), ('phone', 'Phone'), ('chat', 'Live Chat'), ('chatbot', 'AI Chatbot'), ('api', 'API/Integrations'), ('internal', 'Internal/Staff-created'), ('customer_portal', 'Customer Portal'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='web', help_text='How the ticket was created', max_length=20, null=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Universally unique identifier for the ticket', null=True, unique=True)),
                ('is_guest_ticket', models.BooleanField(default=False, help_text='Whether this ticket was created by a guest (non-authenticated user)')),
                ('guest_name', models.CharField(blank=True, help_text='Name of guest who created the ticket', max_length=255, null=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email of guest who created the ticket', max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone number of guest who created the ticket', max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('type', models.CharField(choices=[('question', 'Question'), ('incident', 'Incident'), ('problem', 'Problem'), ('task', 'Task')], default='question', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('merged_at', models.DateTimeField(blank=True, help_text='When this ticket was merged', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Agent assigned to handle the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, help_text='Communication channel through which this ticket was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='settings.channel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.department')),
                ('group', models.ForeignKey(blank=True, help_text='Assignment group for the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Parent ticket this ticket was merged into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tickets', to='ticket.ticket')),
                ('requester', models.ForeignKey(blank=True, help_text='Person who submitted the ticket (null for guest tickets)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, help_text='Users watching this ticket for updates', related_name='watching_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('watcher_added', 'Watcher Added'), ('watcher_removed', 'Watcher Removed'), ('department_changed', 'Department Changed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed'), ('workitem_added', 'Work Item Added'), ('workitem_updated', 'Work Item Updated'), ('workitem_status_changed', 'Work Item Status Changed'), ('workitem_completed', 'Work Item Completed'), ('ticket_merged', 'Ticket Merged'), ('reopened', 'Ticket Reopened')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like old_value, new_value, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ticket.ticket')),
            ],
            options={
                'verbose_name_plural': 'Activity streams',
                'db_table': 'ticket_activity_stream',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the uploaded file', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal attachments are only visible to agents')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Comment content')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment objects with url, name, size, type')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note visible only to agents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, help_text='Users mentioned in this comment', related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket.ticketcomment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket.ticket')),
            ],
            options={
                'db_table': 'ticket_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('work_notes', models.TextField(blank=True, help_text='Notes added when completing the work item')),
                ('due_date', models.DateField(blank=True, help_text='Work item due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='User assigned to complete the work item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created the work item', on_delete=django.db.models.deletion.CASCADE, related_name='created_work_items', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket this work item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='ticket.ticket')),
            ],
            options={
                'db_table': 'ticket_work_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='ticket_status_272d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'status'], name='ticket_assigne_576cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester'], name='ticket_request_a36d96_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='ticket_priorit_07049d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitystream',
            index=models.Index(fields=['ticket', '-created_at'], name='ticket_acti_ticket__b3e91a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitystream',
            index=models.Index(fields=['activity_type'], name='ticket_acti_activit_e57c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitystream',
            index=models.Index(fields=['actor'], name='ticket_acti_actor_i_51a702_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', '-created_at'], name='ticket_comm_ticket__7e1384_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['author'], name='ticket_comm_author__e2d82b_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['ticket', 'status'], name='ticket_work_ticket__fdf213_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assignee'], name='ticket_work_assigne_ad484e_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['due_date'], name='ticket_work_due_dat_a982da_idx'),
        ),
    ]
