# Generated by Django 5.0.2 on 2026-05-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_completed', models.BooleanField(default=False)),
                ('channels_completed', models.BooleanField(default=False)),
                ('users_groups_completed', models.BooleanField(default=False)),
                ('sla_completed', models.BooleanField(default=False)),
                ('emails_smtp_completed', models.BooleanField(default=False)),
                ('notifications_completed', models.BooleanField(default=False)),
                ('modules_data', models.JSONField(blank=True, default=dict)),
                ('channels_data', models.JSONField(blank=True, default=dict)),
                ('users_groups_data', models.JSONField(blank=True, default=dict)),
                ('sla_data', models.JSONField(blank=True, default=dict)),
                ('emails_smtp_data', models.JSONField(blank=True, default=dict)),
                ('notifications_data', models.JSONField(blank=True, default=dict)),
                ('current_step', models.IntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imd_onboarding_progress',
            },
        ),
    ]
