# Generated by Django 5.0.2 on 2026-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_kb_article_approved',
            field=models.BooleanField(default=False, help_text='When a knowledge base article is approved'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_kb_article_published',
            field=models.BooleanField(default=False, help_text='When a knowledge base article is published'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_kb_article_updated',
            field=models.BooleanField(default=False, help_text='When a knowledge base article is updated'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_kb_feedback_received',
            field=models.BooleanField(default=False, help_text='When feedback is received on a knowledge base article'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_sla_resolution_breached',
            field=models.BooleanField(default=False, help_text='When a ticket has breached resolution SLA'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_sla_resolution_warning',
            field=models.BooleanField(default=False, help_text='When a ticket is approaching resolution SLA breach'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_sla_response_breached',
            field=models.BooleanField(default=False, help_text='When a ticket has breached first response SLA'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_sla_response_warning',
            field=models.BooleanField(default=False, help_text='When a ticket is approaching first response SLA breach'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_updated', 'Ticket Updated'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_priority_changed', 'Ticket Priority Changed'), ('ticket_merged', 'Ticket Merged'), ('new_activity_notice', 'New Activity Notice'), ('new_message_auto_response', 'Message Auto Response'), ('new_ticket_notice', 'New Ticket Notice (Agent)'), ('response_reply_template', 'Agent Response Reply'), ('internal_activity_alert', 'Internal Activity Alert'), ('new_message_alert', 'New Message Alert (Agent)'), ('overdue_ticket_alert', 'Overdue Ticket Alert'), ('ticket_transfer_alert', 'Ticket Transfer Alert'), ('task_new_activity_alert', 'Task Activity Alert (Agent)'), ('task_new_activity_notice', 'Task Activity Notice (User)'), ('new_task_alert', 'New Task Alert'), ('overdue_task_alert', 'Overdue Task Alert'), ('task_assignment_alert', 'Task Assignment Alert'), ('task_transfer_alert', 'Task Transfer Alert'), ('sla_reminder', 'SLA Reminder'), ('sla_escalation_notice_task', 'SLA Escalation Notice (Task)'), ('sla_escalation_notice', 'SLA Escalation Notice (Ticket)'), ('sla_first_response_breach', 'First Response SLA Breach'), ('sla_resolution_breach', 'Resolution SLA Breach'), ('sla_resolved_notice', 'Ticket Resolved Within SLA'), ('sla_breach_warning', 'SLA Breach Warning'), ('sla_breached', 'SLA Breached'), ('comment_add_notice', 'Comment Added Notice'), ('comment_reply_notice', 'Comment Reply Notice'), ('user_mentioned', 'User Mentioned in Ticket'), ('welcome_user', 'Welcome Email'), ('password_reset', 'Password Reset'), ('kb_article_published', 'KB Article Published'), ('kb_article_updated', 'KB Article Updated'), ('kb_article_approved', 'KB Article Approved'), ('kb_article_rejected', 'KB Article Rejected'), ('weekly_report', 'Weekly Report'), ('custom', 'Custom Template')], help_text='Template type', max_length=50, unique=True),
        ),
    ]
