# Generated by Django 5.0.2 on 2026-05-04 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Universally unique identifier for the task', null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('due_date', models.DateField(blank=True, help_text='Task due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overdue_notification_sent', models.BooleanField(default=False, help_text='Has overdue notification been sent?')),
                ('due_soon_notification_sent', models.BooleanField(default=False, help_text='Has due soon notification been sent?')),
                ('assignee', models.ForeignKey(blank=True, help_text='User assigned to complete the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('converted_from_ticket', models.ForeignKey(blank=True, help_text='Original ticket if this task was converted from a ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_tasks', to='ticket.ticket')),
                ('created_by', models.ForeignKey(help_text='User who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Assignment group for the task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group')),
                ('related_ticket', models.ForeignKey(blank=True, help_text='Ticket this task is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='ticket.ticket')),
                ('watchers', models.ManyToManyField(blank=True, help_text='Users watching this task for updates', related_name='watching_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('watcher_added', 'Watcher Added'), ('watcher_removed', 'Watcher Removed'), ('group_changed', 'Group Changed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like old_value, new_value, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'Task activity streams',
                'db_table': 'task_activity_stream',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the uploaded file', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Comment content')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment objects with url, name, size, type')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note visible only to agents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'db_table': 'task_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_at'], name='task_status_b8a06a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='task_assigne_1cbd93_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='task_created_c32358_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_priorit_f00456_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_dat_6ddd76_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivitystream',
            index=models.Index(fields=['task', '-created_at'], name='task_activi_task_id_8ce6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivitystream',
            index=models.Index(fields=['activity_type'], name='task_activi_activit_544ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivitystream',
            index=models.Index(fields=['actor'], name='task_activi_actor_i_ddd7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', '-created_at'], name='task_commen_task_id_de4495_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['author'], name='task_commen_author__9499f3_idx'),
        ),
    ]
